messages:
  totem-zombie-spawn:
    success: 'TotemZombie spawned!'
    fail: 'TotemZombie already spawned!'
  totem-zombie-despawn:
    success: 'TotemZombie despawned!'
    fail: 'TotemZombie not spawned!'
  reload:
    success: 'TotemZombie reloaded!'
  error:
    player-only: "This command can only be executed by a player!"
    no-args: "Please provide an argument!"
    no-permission: "You don't have permission to execute this command!"
zombie-totem:
  display-name: '&aTotemZombie'